apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: storage
  labels:
    app: syncthing
spec:
  type: ClusterIP
  ports:
    - port: 8384
      targetPort: 8384
      protocol: TCP
      name: http
    - port: 22000
      targetPort: 22000
      protocol: TCP
      name: sync-tcp
    - port: 22000
      targetPort: 22000
      protocol: UDP
      name: sync-udp
    - port: 21027
      targetPort: 21027
      protocol: UDP
      name: discovery
  selector:
    app: syncthing
