apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: storage
  annotations:
    metallb.io/load-balancer-ip: 10.0.0.100
spec:
  type: LoadBalancer
  ports:
  - port: 445
    targetPort: 445
    name: smb
  selector:
    app: samba
