apiVersion: apps/v1
kind: Deployment
metadata:
  name: metube
  namespace: media
  labels:
    app: metube
spec:
  replicas: 0
  selector:
    matchLabels:
      app: metube
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metube
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1" # Fix potential DNS resolution issues with external domains (avoiding search domain overhead)
      initContainers:
        - name: create-dirs
          image: busybox
          command: ['sh', '-c', 'mkdir -p /mnt/video/Download /mnt/data/Musique_sync']
          volumeMounts:
            - name: video-vol
              mountPath: /mnt/video
            - name: data-vol
              mountPath: /mnt/data
      containers:
        - name: metube
          image: ghcr.io/alexta69/metube:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: UID
              value: "1000"
            - name: GID
              value: "1000"
            - name: DOWNLOAD_DIR
              value: "/mnt/video/Download"
            - name: AUDIO_DOWNLOAD_DIR
              value: "/mnt/data/Musique_sync"
            - name: STATE_DIR
              value: "/data"
            - name: DEFAULT_OPTION_PLAYLIST_STRICT_MODE
              value: "true"
            - name: DEFAULT_OPTION_PLAYLIST_ITEM_LIMIT
              value: "50"
          ports:
            - name: http
              containerPort: 8081
          volumeMounts:
            - name: video-vol
              mountPath: /mnt/video
            - name: data-vol
              mountPath: /mnt/data
            - name: state
              mountPath: /data
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: video-vol
          persistentVolumeClaim:
            claimName: pvc-media-video
        - name: data-vol
          persistentVolumeClaim:
            claimName: pvc-media-data
        - name: state
          persistentVolumeClaim:
            claimName: metube-state
