gha-runner-scale-set-controller:
  flags:
    logLevel: info

gha-runner-scale-set:
  githubConfigUrl: "https://github.com/abugeia"
  githubConfigSecret: controller-manager
  minRunners: 0
  maxRunners: 5
  runnerScaleSetName: "homelab-runner"
  controllerServiceAccount:
    namespace: storage
    name: gha-runner-scale-set-controller
