# Values for MetalLB chart 0.15.3
# Custom L2 configuration is handled separately in conf/metallb.yaml

controller:
  # Permet d'avoir des logs plus verbeux si besoin de debug
  logLevel: info
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

speaker:
  logLevel: info
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  # Désactivation de FRR car nous sommes en mode L2
  frr:
    enabled: false

prometheus:
  enabled: false # Désactivé par défaut, peut être activé si Prometheus est présent
