# Values for MetalLB chart 0.15.3
# Custom L2 configuration is handled separately in conf/metallb.yaml

prometheus:
  enabled: false
  serviceMonitor:
    enabled: false
    # namespace: observability # Si Prometheus est là

controller:
  logLevel: info
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

speaker:
  logLevel: info
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
  frr:
    enabled: false
  # Permet au speaker d'envoyer des ARP même si Cilium est là
  # (Cilium peut bloquer les ARP non autorisés)
  # Mais ici on part du principe que Cilium ne fait pas d'annonces L2.
