apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: media
  labels:
    app: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:latest
          imagePullPolicy: IfNotPresent
          args:
            - --database
            - /database/filebrowser.db
            - --root
            - /srv
            - --noauth # Bypasses internal auth since we use TinyAuth
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: vol-data
              mountPath: /srv/data
            - name: vol-video
              mountPath: /srv/video
            - name: config
              mountPath: /database
            - name: immich-library
              mountPath: /srv/immich-media
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: vol-data
          persistentVolumeClaim:
            claimName: pvc-media-data
        - name: vol-video
          persistentVolumeClaim:
            claimName: pvc-media-video
        - name: config
          persistentVolumeClaim:
            claimName: filebrowser-config
        - name: immich-library
          persistentVolumeClaim:
            claimName: immich-library
