apiVersion: v1
kind: Service
metadata:
  name: boten-anna
  namespace: boten-anna
spec:
  selector:
    app: boten-anna
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
