---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wetty
  namespace: admin
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: security-tinyauth-protect@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Web Terminal"
    gethomepage.dev/group: "Admin"
    gethomepage.dev/icon: "si-linux"
    gethomepage.dev/name: "Terminal proxmox"
    gethomepage.dev/href: "https://px.valab.top"
spec:
  ingressClassName: traefik
  rules:
    - host: px.valab.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wetty
                port:
                  number: 3000
