---
apiVersion: v1
kind: Service
metadata:
  name: wetty
  namespace: admin
  labels:
    app: wetty
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: wetty
  type: ClusterIP
