apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: media
  labels:
    app: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      containers:
        - name: navidrome
          image: deluan/navidrome:0.56.0
          ports:
            - containerPort: 4533
              name: http
          env:
            - name: ND_SCANTYPES
              value: "m4a,mp3,flac,ogg"
            - name: ND_MUSICFOLDER
              value: "/music/metube_music"
            - name: ND_DATAFOLDER
              value: "/data"
            - name: ND_BASEURL
              value: ""
            - name: ND_REVERSEPROXYUSERHEADER
              value: "Remote-Email"
            - name: ND_REVERSEPROXYWHITELIST
              value: "0.0.0.0/0"
            - name: ND_LOGLEVEL
              value: "debug"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: music
              mountPath: /music
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: navidrome-data
        - name: music
          persistentVolumeClaim:
            claimName: media-data
