apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome
  namespace: media
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: security-tinyauth-protect@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Music Server"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "navidrome.png"
    gethomepage.dev/name: "Navidrome"
    gethomepage.dev/href: "https://music.valab.top"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - music.valab.top
        - navidrome.valab.top
      secretName: navidrome-tls
  rules:
    - host: music.valab.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: navidrome
                port:
                  name: http
    - host: navidrome.valab.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: navidrome
                port:
                  name: http
