apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: media
  labels:
    app: navidrome
spec:
  ports:
    - port: 4533
      targetPort: 4533
      name: http
  selector:
    app: navidrome
