---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wetty
  namespace: admin
  labels:
    app: wetty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wetty
  template:
    metadata:
      labels:
        app: wetty
    spec:
      containers:
        - name: wetty
          image: wettyoss/wetty:latest
          args: ["--ssh-host", "$(SSHHOST)", "--ssh-port", "$(SSHPORT)", "--ssh-user", "$(SSHUSER)", "--base", "/"]
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: SSHHOST
              value: "10.0.0.10"
            - name: SSHPORT
              value: "22"
            - name: SSHUSER
              value: "root"
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
