---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wetty
  namespace: admin
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: security-tinyauth-protect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: sh.valab.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wetty
                port:
                  number: 3000
