apiVersion: apps/v1
kind: Deployment
metadata:
  name: omni-tools
  namespace: tools
  labels:
    app: omni-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omni-tools
  template:
    metadata:
      labels:
        app: omni-tools
    spec:
      containers:
        - name: omni-tools
          image: iib0011/omni-tools:latest
          ports:
            - containerPort: 80
              name: web
