apiVersion: v1
kind: Service
metadata:
  name: omni-tools
  namespace: tools
  labels:
    app: omni-tools
spec:
  selector:
    app: omni-tools
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
